<a href="https://colab.research.google.com/github/ehpub/kfq_ML_2023/blob/main/2023_kfq_%EB%A8%B8%EC%8B%A0%EB%9F%AC%EB%8B%9D_%EA%B0%90%EC%84%B1%EB%B6%84%EC%84%9D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

강의 교재 : https://wikibook.co.kr/pymlrev2/

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
path = '/content/drive/MyDrive/mldata/labeledTrainData.tsv'

In [4]:
df = pd.read_csv(path,header=0,sep='\t',quoting=3)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   id         25000 non-null  object
 1   sentiment  25000 non-null  int64 
 2   review     25000 non-null  object
dtypes: int64(1), object(2)
memory usage: 586.1+ KB


In [5]:
df.head(3)

id  sentiment                                             review
0  "5814_8"          1  "With all this stuff going down at the moment ...
1  "2381_9"          1  "\"The Classic War of the Worlds\" by Timothy ...
2  "7759_3"          0  "The film starts with a manager (Nicholas Bell...

In [6]:
df['sentiment'].value_counts()

1    12500
0    12500
Name: sentiment, dtype: int64

In [7]:
df['review'][0]

'"With all this stuff going down at the moment with MJ i\'ve started listening to his music, watching the odd documentary here and there, watched The Wiz and watched Moonwalker again. Maybe i just want to get a certain insight into this guy who i thought was really cool in the eighties just to maybe make up my mind whether he is guilty or innocent. Moonwalker is part biography, part feature film which i remember going to see at the cinema when it was originally released. Some of it has subtle messages about MJ\'s feeling towards the press and also the obvious message of drugs are bad m\'kay.<br /><br />Visually impressive but of course this is all about Michael Jackson so unless you remotely like MJ in anyway then you are going to hate this and find it boring. Some may call MJ an egotist for consenting to the making of this movie BUT MJ and most of his fans would say that he made it for the fans which if true is really nice of him.<br /><br />The actual feature film bit when it finally

In [8]:
import re

In [9]:
df['review'] = df['review'].str.replace("<br />","")
df['review'][0]

'"With all this stuff going down at the moment with MJ i\'ve started listening to his music, watching the odd documentary here and there, watched The Wiz and watched Moonwalker again. Maybe i just want to get a certain insight into this guy who i thought was really cool in the eighties just to maybe make up my mind whether he is guilty or innocent. Moonwalker is part biography, part feature film which i remember going to see at the cinema when it was originally released. Some of it has subtle messages about MJ\'s feeling towards the press and also the obvious message of drugs are bad m\'kay.Visually impressive but of course this is all about Michael Jackson so unless you remotely like MJ in anyway then you are going to hate this and find it boring. Some may call MJ an egotist for consenting to the making of this movie BUT MJ and most of his fans would say that he made it for the fans which if true is really nice of him.The actual feature film bit when it finally starts is only on for 2

In [10]:
df['review'] = df['review'].apply(lambda x:re.sub("[^a-zA-Z]"," ",x))
df['review'][0]

' With all this stuff going down at the moment with MJ i ve started listening to his music  watching the odd documentary here and there  watched The Wiz and watched Moonwalker again  Maybe i just want to get a certain insight into this guy who i thought was really cool in the eighties just to maybe make up my mind whether he is guilty or innocent  Moonwalker is part biography  part feature film which i remember going to see at the cinema when it was originally released  Some of it has subtle messages about MJ s feeling towards the press and also the obvious message of drugs are bad m kay Visually impressive but of course this is all about Michael Jackson so unless you remotely like MJ in anyway then you are going to hate this and find it boring  Some may call MJ an egotist for consenting to the making of this movie BUT MJ and most of his fans would say that he made it for the fans which if true is really nice of him The actual feature film bit when it finally starts is only on for    m

In [11]:
text = "I am a boy. He's 20!!! korea."
re.sub("[^a-zA-Z]"," ",text)

'I am a boy  He s       korea '

In [12]:
df.columns

Index(['id', 'sentiment', 'review'], dtype='object')

In [13]:
data = df[['review']]
label = df['sentiment']

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
x_train,x_test,y_train,y_test = train_test_split(data,label)

In [16]:
x_train.shape,x_test.shape

((18750, 1), (6250, 1))

In [17]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, roc_auc_score

In [18]:
pipeline = Pipeline([
    ('cnt_vect',CountVectorizer(stop_words="english",
                                ngram_range=(1,2))),
    ('lr',LogisticRegression(C=10))
])
pipeline.fit(x_train['review'],y_train)
pred = pipeline.predict(x_test['review'])
pred_proba = pipeline.predict_proba(x_test['review'])[:,1]
print(accuracy_score(y_test,pred))
print(roc_auc_score(y_test,pred_proba))

KeyboardInterrupt: ignored

In [ ]:
cv = CountVectorizer(stop_words="english",
                                ngram_range=(1,2))
cv.fit(data['review'])
x_train_cv = cv.transform(x_train['review'])
x_test_cv = cv.transform(x_test['review'])

model = LogisticRegression(C=10)
model.fit(x_train_cv,y_train)
pred = model.predict(x_test_cv)
pred_proba = model.predict_proba(x_test_cv)[:,1]
print(accuracy_score(y_test,pred))
print(roc_auc_score(y_test,pred_proba))

In [ ]:
pipeline = Pipeline([
    ('tfidf_vect',TfidfVectorizer(stop_words="english",
                                ngram_range=(1,2))),
    ('lr',LogisticRegression(C=10))
])
pipeline.fit(x_train['review'],y_train)
pred = pipeline.predict(x_test['review'])
pred_proba = pipeline.predict_proba(x_test['review'])[:,1]
print(accuracy_score(y_test,pred))
print(roc_auc_score(y_test,pred_proba))

In [ ]:
import nltk

In [ ]:
nltk.download('all')

In [19]:
from nltk.corpus import wordnet as wn

In [ ]:
term = 'apple'
synsets = wn.synsets(term)
print(synsets)

In [ ]:
term = 'banana'
synsets = wn.synsets(term)
print(synsets)

In [ ]:
term = 'do'
synsets = wn.synsets(term)
print(synsets)

In [ ]:
term = 'take'
synsets = wn.synsets(term)
print(synsets)

In [ ]:
term = 'present'
synsets = wn.synsets(term)
for syn in synsets:
  print("###품사:",syn.lexname(), syn.lemma_names())
  print("정의:",syn.definition())

In [ ]:
term = 'lion'
synsets = wn.synsets(term)
for syn in synsets:
  print("###품사:",syn.lexname())
  print("정의:",syn.definition())

In [ ]:
help(wn.synsets)

In [ ]:
word = wn.synset('tree.n.01')
print("###품사:",word.lexname())
print("정의:",word.definition())

In [ ]:
word = wn.synset('tiger.n.02')
print("###품사:",word.lexname())
print("정의:",word.definition())

In [ ]:
tree = wn.synset('tree.n.01')
lion = wn.synset('lion.n.01')
tiger = wn.synset('tiger.n.02')
cat = wn.synset('cat.n.01')
dog = wn.synset('dog.n.01')
entities = [tree,lion,tiger,cat,dog]

In [ ]:

ens = []
for entity in entities:
  ens.append(entity.name().split('.')[0])
#ens = [entity.name().split('.')[0] for entity in entities]
ens

In [ ]:
similarities = []
for entity1 in entities:
  ss = []
  for entity2 in entities:
    s = entity1.path_similarity(entity2)
    ss.append(round(s,2))
  similarities.append(ss)
similarities

In [ ]:
df = pd.DataFrame(similarities,
                  columns = ens ,
                  index=ens)
df

In [20]:
from nltk.corpus import sentiwordnet as swn

In [ ]:
list(swn.senti_synsets('father'))

In [ ]:
father = swn.senti_synset('father.n.01')
print(father.pos_score())
print(father.neg_score())
print(father.obj_score())

In [ ]:
mother = swn.senti_synset('mother.n.01')
print(mother.pos_score())
print(mother.neg_score())
print(mother.obj_score())

In [ ]:
word = swn.senti_synset('happy.a.01')
print(word.pos_score())
print(word.neg_score())
print(word.obj_score())

In [21]:
def penn_to_wn(tag):
  if tag.startswith('J'):
    return wn.ADJ #형용사
  if tag.startswith('N'):
    return wn.NOUN #명사
  if tag.startswith('R'):
    return wn.ADV #부사
  if tag.startswith('V'):
    return wn.VERB #동사

In [27]:
st = x_train['review'].values[0]

In [29]:
from nltk.stem import WordNetLemmatizer
from nltk.corpus import sentiwordnet as swn
from nltk import sent_tokenize, word_tokenize,pos_tag

In [38]:
import nltk

In [39]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [ ]:
nltk.download('all')

In [140]:
def swn_polarity(text):
  sentiment = 0.0
  tokens_count = 0
  lem = WordNetLemmatizer()
  raw_sentences = sent_tokenize(text)
  for sentence in raw_sentences:
    words = word_tokenize(sentence)
    tws = pos_tag(words)
    for word,tag in tws:
      wn_tag = penn_to_wn(tag)
      #명사, 형용사, 부사를 제외한 나머지는 스킵
      if wn_tag not in (wn.NOUN , wn.ADJ, wn.ADV):
        continue
      lemma = lem.lemmatize(word,pos=wn_tag)
      if not lemma: #현재까지는 발생하지 않았음
        continue
      synsets = wn.synsets(lemma,pos=wn_tag)
      if not synsets: #사전에 없는 단어는 스킵
        continue
      synset = synsets[0]
      ss = swn.senti_synset(synset.name())
      sentiment += (ss.pos_score() - ss.neg_score())
      tokens_count +=1 #모든 절차에서 스킵하지 않은 단어 수
  if tokens_count == 0:
    return 0
  if sentiment>=0:
    return 1
  return 0

In [116]:
df['sentiment'].value_counts()

1    12500
0    12500
Name: sentiment, dtype: int64

In [141]:
df['pred'] = df['review'].apply(swn_polarity)

In [142]:
df['pred'].describe()

count    25000.000000
mean         0.547920
std          0.497708
min          0.000000
25%          0.000000
50%          1.000000
75%          1.000000
max          1.000000
Name: pred, dtype: float64

In [77]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score
from sklearn.metrics import roc_auc_score
import numpy as np

In [143]:
label = df['sentiment'].values
pred = df['pred'].values

In [144]:
print(confusion_matrix(label,pred))

[[7664 4836]
 [3638 8862]]


In [150]:
print(accuracy_score(label,pred))
print(precision_score(label,pred))
print(recall_score(label,pred))
print(f1_score(label,pred))
print(roc_auc_score(label,pred))

0.66104
0.6469557599649584
0.70896
0.6765401939079319
0.6610400000000001


In [151]:
from nltk.sentiment.vader import SentimentIntensityAnalyzer

In [152]:
sa = SentimentIntensityAnalyzer()

In [153]:
sa.polarity_scores(df['review'][0])

{'neg': 0.13, 'neu': 0.743, 'pos': 0.127, 'compound': -0.7943}

In [154]:
def vader_polarity(text,th=0.1):
  sa = SentimentIntensityAnalyzer()
  score = sa.polarity_scores(text)['compound']
  return int(score>=th)

In [157]:
pred2 = df['review'].apply(vader_polarity)

In [158]:
print(confusion_matrix(label,pred2))
print(accuracy_score(label,pred2))
print(precision_score(label,pred2))
print(recall_score(label,pred2))
print(f1_score(label,pred2))
print(roc_auc_score(label,pred2))

[[ 6744  5756]
 [ 1858 10642]]
0.69544
0.6489815831198926
0.85136
0.7365215585853693
0.6954400000000001


In [161]:
pred3 = df['review'].apply(lambda x:vader_polarity(x,-0.05))
print(confusion_matrix(label,pred3))
print(accuracy_score(label,pred3))
print(precision_score(label,pred3))
print(recall_score(label,pred3))
print(f1_score(label,pred3))
print(roc_auc_score(label,pred3))

[[ 6475  6025]
 [ 1753 10747]]
0.68888
0.640770331504889
0.85976
0.7342853238589777
0.68888
