<a href="https://colab.research.google.com/github/ehpub/kfq_ML_2023/blob/main/2023_kfq_%EB%A8%B8%EC%8B%A0%EB%9F%AC%EB%8B%9D_%ED%86%A0%ED%94%BD_%EB%AA%A8%EB%8D%B8%EB%A7%81.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

강의 교재 : https://wikibook.co.kr/pymlrev2/

In [2]:
from sklearn.datasets import fetch_20newsgroups
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.decomposition import LatentDirichletAllocation

In [9]:
cats = ['rec.motorcycles','rec.sport.baseball',
        'comp.graphics','comp.windows.x',
        'talk.politics.mideast',
        'soc.religion.christian',
        'sci.electronics','sci.med']

In [13]:
news = fetch_20newsgroups(subset='all',
                   remove=('headers','footers','quotes'),
                  categories=cats)

In [25]:
news.target_names

['comp.graphics',
 'comp.windows.x',
 'rec.motorcycles',
 'rec.sport.baseball',
 'sci.electronics',
 'sci.med',
 'soc.religion.christian',
 'talk.politics.mideast']

In [16]:
cv = CountVectorizer(max_df=0.95,
                     max_features=1000,
                     min_df=0.005,
                     stop_words='english',
                     ngram_range=(1,2)
                     )
cv_data = cv.fit_transform(news.data)
cv_data.shape

(7862, 1000)

In [17]:
news.data[0]

'\nWhat sort of traffic is generated with the X-calls?  I am curious to find\nout the required bandwidth that a link must have  if one machine running\nDV/X is supporting multiple users (clients) and we require adequate response\ntime.  Anyone have any ideas ??  \n\n\n'

In [22]:
import numpy as np
np.unique(news.target,return_counts=True)

(array([0, 1, 2, 3, 4, 5, 6, 7]),
 array([973, 988, 996, 994, 984, 990, 997, 940]))

In [23]:
model = LatentDirichletAllocation(n_components=8)
model.fit(cv_data)
model.components_

array([[4.31874306e+01, 1.25038310e-01, 8.46551142e+01, ...,
        2.84385967e-01, 4.27573323e+01, 1.25003512e-01],
       [3.84850795e+01, 3.10200138e+02, 2.65050604e+01, ...,
        4.82564250e+01, 8.15063250e+01, 1.25143648e-01],
       [3.63471407e+00, 2.19104937e+01, 1.25133248e-01, ...,
        1.25088170e-01, 1.03654440e+02, 1.25102665e-01],
       ...,
       [1.25217692e-01, 1.54579315e+02, 1.25127050e-01, ...,
        2.28530217e+02, 8.42352815e+00, 1.25093013e-01],
       [5.81948942e+00, 7.55098066e+00, 1.25146606e-01, ...,
        1.25027265e-01, 1.29020986e-01, 1.23925491e+00],
       [2.50493547e+02, 6.71179705e+00, 6.91423689e+01, ...,
        4.71952306e-01, 1.31519496e+01, 1.25016889e-01]])

In [24]:
model.components_.shape

(8, 1000)

In [32]:
fns = cv.get_feature_names_out()
no_top = 10
for i, topic in enumerate(model.components_):
  print("No.",i )#, ":",news.target_names[i])
  tw_indexes = topic.argsort()[::-1] #역순정렬
  top_indexes = tw_indexes[:no_top]
  words = [fns[i] for i in top_indexes]
  print(words)

No. 0 : comp.graphics
['god', 'people', 'jesus', 'church', 'believe', 'does', 'christ', 'think', 'say', 'christian']
No. 1 : comp.windows.x
['armenian', 'armenians', 'people', 'said', 'turkish', '10', 'children', 'health', '12', 'armenia']
No. 2 : rec.motorcycles
['don', 'just', 'think', 'like', 'know', 'time', 'good', 'people', 'year', 'say']
No. 3 : rec.sport.baseball
['image', 'jpeg', 'dos', 'file', 'color', 'gif', 'windows', 'images', 'files', 'format']
No. 4 : sci.electronics
['edu', 'graphics', 'data', 'mail', 'information', 'available', 'software', 'com', 'send', 'computer']
No. 5 : sci.med
['israel', 'jews', 'jewish', 'israeli', 'arab', 'university', 'new', 'war', 'state', 'history']
No. 6 : soc.religion.christian
['like', 'know', 'use', 'does', 'just', 've', 'thanks', 'used', 'don', 'bike']
No. 7 : talk.politics.mideast
['file', 'window', 'server', 'use', 'program', 'motif', 'sun', 'widget', 'com', 'mit']


In [43]:
b_news = fetch_20newsgroups(subset='all',
                   remove=('headers','footers','quotes'),
                  categories=['rec.sport.baseball'])

In [45]:
len(b_news.data)

994

In [47]:
bcv = CountVectorizer(max_df=0.95,
                     max_features=1000,
                     min_df=0.005,
                     stop_words='english',
                     ngram_range=(1,2)
                     )
bcv_data = bcv.fit_transform(b_news.data)
bcv_data.shape

(994, 1000)

In [48]:
bmodel = LatentDirichletAllocation(n_components=8)
bmodel.fit(bcv_data)
bmodel.components_

array([[1.25041863e-01, 1.25019025e-01, 1.25022721e-01, ...,
        2.66104173e+00, 1.25005533e-01, 5.11066671e+00],
       [1.25042860e-01, 1.25022753e-01, 1.25005507e-01, ...,
        7.98486628e+00, 1.25007458e-01, 1.25050083e-01],
       [5.18312703e+01, 5.81433661e+01, 1.51659400e-01, ...,
        2.62109363e+00, 1.25060226e-01, 1.39572539e+01],
       ...,
       [1.25005048e-01, 1.25145402e-01, 1.25113540e-01, ...,
        6.68690259e+00, 9.76908102e+00, 1.59031275e-01],
       [1.25026690e-01, 2.01060502e+01, 1.25111790e-01, ...,
        1.45279754e+00, 1.78078105e+00, 1.25000008e-01],
       [1.32418517e+02, 1.25206134e-01, 1.23789034e+02, ...,
        1.25208900e-01, 1.25012908e-01, 1.25000005e-01]])

In [49]:
fns = bcv.get_feature_names_out()

In [50]:
no_top = 10
for i, topic in enumerate(bmodel.components_):
  print("No.",i )#, ":",news.target_names[i])
  tw_indexes = topic.argsort()[::-1] #역순정렬
  top_indexes = tw_indexes[:no_top]
  words = [fns[i] for i in top_indexes]
  print(words)

No. 0
['game', 'don', 'games', 'gant', 'time', 'baseball', 'ball', 'like', 'think', 'alomar']
No. 1
['game', 'just', 'baseball', 'like', 'think', 'don', 'fan', 'know', 'games', 'fans']
No. 2
['000', '00', 'list', 'players', 'baseball', 'league', 'time', 'team', 'uniforms', 'think']
No. 3
['year', 'runs', 'game', '10', 'average', 'win', 'pitching', 'run', '12', 'team']
No. 4
['braves', 'team', 'pitcher', 'game', 'home', 'base', 'brian', 'edu', 'does', 'runner']
No. 5
['year', 'good', 'think', 'players', 'don', 'better', 'just', 'clutch', 'hit', 'know']
No. 6
['morris', 'sox', 'games', 'team', 'red', 'clemens', 'jays', 'year', 'red sox', '333']
No. 7
['03', '02', '04', '00', '01', 'won', 'lost', '05', '06', 'cubs']
