<a href="https://colab.research.google.com/github/ehpub/kfq_ML_2023/blob/main/%EB%A8%B8%EC%8B%A0%EB%9F%AC%EB%8B%9D_%EC%82%AC%EC%9D%B4%ED%82%B7%EB%9F%B0%EC%9C%BC%EB%A1%9C_%EC%8B%9C%EC%9E%91.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [93]:
import sklearn

In [94]:
help(sklearn)

Help on package sklearn:

NAME
    sklearn

DESCRIPTION
    Machine learning module for Python
    
    sklearn is a Python module integrating classical machine
    learning algorithms in the tightly-knit world of scientific Python
    packages (numpy, scipy, matplotlib).
    
    It aims to provide simple and efficient solutions to learning problems
    that are accessible to everybody and reusable in various contexts:
    machine-learning as a versatile tool for science and engineering.
    
    See http://scikit-learn.org for complete documentation.

PACKAGE CONTENTS
    __check_build (package)
    _build_utils (package)
    _config
    _distributor_init
    _isotonic
    _loss (package)
    _min_dependencies
    base
    calibration
    cluster (package)
    compose (package)
    conftest
    covariance (package)
    cross_decomposition (package)
    datasets (package)
    decomposition (package)
    discriminant_analysis
    dummy
    ensemble (package)
    exceptions
    experime

## 첫 번째 머신러닝

In [95]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
import pandas as pd

In [96]:
iris = load_iris()

In [97]:
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [98]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [99]:
iris_data = iris.data
iris_data.shape

(150, 4)

In [100]:
iris_label = iris.target

In [101]:
import numpy as np
np.unique(iris_label,return_counts=True)

(array([0, 1, 2]), array([50, 50, 50]))

In [102]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [103]:
df = pd.DataFrame(iris.data,columns=iris.feature_names)
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [104]:
xa = [[x,x] for x in range(100)]
ya = [y for y in range(100)]

In [105]:
x_train, x_test, y_train,y_test = train_test_split(xa,ya)

In [106]:
np.array(x_train).shape, np.array(y_train).shape

((75, 2), (75,))

In [107]:
for i in range(len(x_train)):
  print(x_train[i], ":",y_train[i])

[27, 27] : 27
[30, 30] : 30
[58, 58] : 58
[76, 76] : 76
[70, 70] : 70
[26, 26] : 26
[51, 51] : 51
[61, 61] : 61
[91, 91] : 91
[71, 71] : 71
[5, 5] : 5
[87, 87] : 87
[81, 81] : 81
[10, 10] : 10
[12, 12] : 12
[63, 63] : 63
[4, 4] : 4
[97, 97] : 97
[48, 48] : 48
[37, 37] : 37
[83, 83] : 83
[38, 38] : 38
[18, 18] : 18
[32, 32] : 32
[89, 89] : 89
[0, 0] : 0
[36, 36] : 36
[73, 73] : 73
[13, 13] : 13
[55, 55] : 55
[41, 41] : 41
[60, 60] : 60
[39, 39] : 39
[3, 3] : 3
[2, 2] : 2
[11, 11] : 11
[62, 62] : 62
[14, 14] : 14
[72, 72] : 72
[95, 95] : 95
[88, 88] : 88
[15, 15] : 15
[59, 59] : 59
[99, 99] : 99
[96, 96] : 96
[28, 28] : 28
[46, 46] : 46
[90, 90] : 90
[69, 69] : 69
[40, 40] : 40
[66, 66] : 66
[80, 80] : 80
[9, 9] : 9
[16, 16] : 16
[23, 23] : 23
[49, 49] : 49
[21, 21] : 21
[79, 79] : 79
[74, 74] : 74
[45, 45] : 45
[17, 17] : 17
[57, 57] : 57
[53, 53] : 53
[22, 22] : 22
[86, 86] : 86
[82, 82] : 82
[25, 25] : 25
[94, 94] : 94
[75, 75] : 75
[52, 52] : 52
[68, 68] : 68
[50, 50] : 50
[7, 7] : 7

In [108]:
x_train,x_test,y_train,y_test = train_test_split(
    iris_data,iris_label,test_size=0.2)

In [109]:
x_train.shape, x_test.shape

((120, 4), (30, 4))

In [110]:
model = DecisionTreeClassifier()#모델 생성
model.fit(x_train,y_train)#모델 학습

DecisionTreeClassifier()

In [111]:
pred = model.predict(x_test) #학습한 모델로 예측

In [112]:
print(pred)
print(y_test)

[2 1 2 1 2 0 2 2 0 0 0 2 1 1 0 0 1 1 1 2 1 0 2 0 1 2 2 0 2 1]
[2 1 1 1 2 0 2 2 0 0 0 2 2 1 0 0 1 1 1 2 1 0 2 0 1 2 2 0 2 1]


In [113]:
from sklearn.metrics import accuracy_score

In [114]:
accuracy_score(y_test,pred) #모델 평가

0.9333333333333333

## 프레임워크 익히기

In [115]:
iris_data = load_iris()

In [116]:
type(iris_data)

sklearn.utils._bunch.Bunch

In [117]:
keys = iris_data.keys()
keys

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [118]:
print("특성:",iris_data.feature_names)

특성: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [119]:
print("특성 수:",len(iris_data.feature_names))

특성 수: 4


In [120]:
print("종속 변수 타입:",type(iris_data.target[0]))

종속 변수 타입: <class 'numpy.int64'>


In [121]:
print("타겟 이름:",iris_data.target_names)

타겟 이름: ['setosa' 'versicolor' 'virginica']


In [122]:
print("독립변수 구조:",iris_data.data.shape)

독립변수 구조: (150, 4)


In [123]:
print("종속변수 타입:",type(iris_data.target[0]))

종속변수 타입: <class 'numpy.int64'>


## Model Selection 모듈 소개

In [124]:
iris = load_iris()
train_data = iris.data #독립변수(data,feature,x)
train_label = iris.target #종속변수(label,target,y)

In [125]:
df = DecisionTreeClassifier()
df.fit(train_data,train_label)
pred = df.predict(train_data)
accuracy_score(pred,train_label)

1.0

In [126]:
x_train,x_test,y_train,y_test = train_test_split(
    iris.data,iris.target
)

In [127]:
model = DecisionTreeClassifier() #모델 생성
model.fit(x_train,y_train) #모델 학습
pred = model.predict(x_test) #예측
accuracy_score(y_test,pred) #평가

0.9473684210526315

In [128]:
from sklearn.model_selection import KFold

In [129]:
iris = load_iris()
feature = iris.data
label = iris.target

In [130]:
dt = DecisionTreeClassifier()
kfold = KFold(n_splits=5)

In [131]:
cv_accuracy=[]
n_iter = 0

In [132]:
for train_ind, val_ind in kfold.split(feature):
  x_train,x_val = feature[train_ind],feature[val_ind]
  y_train,y_val = label[train_ind],label[val_ind]

  df.fit(x_train,y_train) #학습
  pred = df.predict(x_val) #예측
  n_iter+=1
  acc = np.round(accuracy_score(pred,y_val),3)
  print(n_iter,"회 교차 검증 accuracy:",acc)
  cv_accuracy.append(acc)
print("평균 accuracy:",np.mean(cv_accuracy))

1 회 교차 검증 accuracy: 1.0
2 회 교차 검증 accuracy: 1.0
3 회 교차 검증 accuracy: 0.833
4 회 교차 검증 accuracy: 0.933
5 회 교차 검증 accuracy: 0.733
평균 accuracy: 0.8997999999999999


In [133]:
df = pd.DataFrame(iris.data,columns = iris.feature_names)
df['label'] =iris.target
df['label'].value_counts()

0    50
1    50
2    50
Name: label, dtype: int64

In [134]:
dt = DecisionTreeClassifier()
kfold = KFold(n_splits=3)
n_iter = 0
xdf = df.drop('label',axis=1)
for train_ind,val_ind in kfold.split(df):
  x_train = xdf.iloc[train_ind]
  x_val = xdf.iloc[val_ind]
  label_train = df['label'].iloc[train_ind]
  label_val = df['label'].iloc[val_ind]
  dt.fit(x_train,label_train) #학습
  pred = dt.predict(x_val) #예측
  n_iter+=1
  acc = np.round(accuracy_score(pred,label_val),3)
  print(n_iter,"====")
  print("학습 데이터:",label_train.value_counts())
  print("검증 데이터:",label_val.value_counts())
  print("평가 accuracy:",acc)

1 ====
학습 데이터: 1    50
2    50
Name: label, dtype: int64
검증 데이터: 0    50
Name: label, dtype: int64
평가 accuracy: 0.0
2 ====
학습 데이터: 0    50
2    50
Name: label, dtype: int64
검증 데이터: 1    50
Name: label, dtype: int64
평가 accuracy: 0.0
3 ====
학습 데이터: 0    50
1    50
Name: label, dtype: int64
검증 데이터: 2    50
Name: label, dtype: int64
평가 accuracy: 0.0


In [135]:
from sklearn.model_selection import StratifiedKFold

In [136]:
dt = DecisionTreeClassifier()
kfold = StratifiedKFold(n_splits=3)
n_iter = 0
xdf = df.drop('label',axis=1)
for train_ind,val_ind in kfold.split(df,df['label']):
  x_train = xdf.iloc[train_ind]
  x_val = xdf.iloc[val_ind]
  label_train = df['label'].iloc[train_ind]
  label_val = df['label'].iloc[val_ind]
  dt.fit(x_train,label_train) #학습
  pred = dt.predict(x_val) #예측
  n_iter+=1
  acc = np.round(accuracy_score(pred,label_val),3)
  print(n_iter,"====")
  print("학습 데이터:",label_train.value_counts())
  print("검증 데이터:",label_val.value_counts())
  print("평가 accuracy:",acc)

1 ====
학습 데이터: 2    34
0    33
1    33
Name: label, dtype: int64
검증 데이터: 0    17
1    17
2    16
Name: label, dtype: int64
평가 accuracy: 0.98
2 ====
학습 데이터: 1    34
0    33
2    33
Name: label, dtype: int64
검증 데이터: 0    17
2    17
1    16
Name: label, dtype: int64
평가 accuracy: 0.92
3 ====
학습 데이터: 0    34
1    33
2    33
Name: label, dtype: int64
검증 데이터: 1    17
2    17
0    16
Name: label, dtype: int64
평가 accuracy: 0.98


In [137]:
from sklearn.model_selection import cross_val_score, cross_validate

In [138]:
data = iris.data
label = iris.target

In [139]:
dt = DecisionTreeClassifier()
scores = cross_val_score(dt,data,label,scoring='accuracy',cv=3)
scores

array([0.98, 0.94, 0.96])

In [140]:
dt = DecisionTreeClassifier()
scores = cross_validate(dt,data,label,
                         scoring=['accuracy','precision','recall'],
                         cv=3)
scores

/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:794: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py", line 115, in __call__
    score = scorer._score(cached_call, estimator, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py", line 282, in _score
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py", line 1954, in precision_score
    p, _, _, _ = precision_recall_fscore_support(
  File "/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py", line 1573, in precision_recall_fscore_support
    labels = _check_set_wise_labels(y_true, y_pred, average, labels, pos_label)
  File "/usr/local/lib/python3.10/dist-packages/sk

{'fit_time': array([0.00454354, 0.00124598, 0.00171542]),
 'score_time': array([0.0050087, 0.0091114, 0.0052526]),
 'test_accuracy': array([0.98, 0.94, 1.  ]),
 'test_precision': array([nan, nan, nan]),
 'test_recall': array([nan, nan, nan])}

In [141]:
x_train,x_test,y_train,y_test = train_test_split(iris.data,
                                                 iris.target)

In [142]:
mds = [1,2,3]
mss = [2,3,4]
for depth in mds:
  for ms in mss:
    dt = DecisionTreeClassifier(max_depth=depth,min_samples_split=ms)
    dt.fit(x_train,y_train)
    pred = dt.predict(x_test)
    print(depth,",",ms,": acc =",accuracy_score(y_test,pred))

1 , 2 : acc = 0.6842105263157895
1 , 3 : acc = 0.6842105263157895
1 , 4 : acc = 0.6842105263157895
2 , 2 : acc = 0.9210526315789473
2 , 3 : acc = 0.9210526315789473
2 , 4 : acc = 0.9210526315789473
3 , 2 : acc = 0.9210526315789473
3 , 3 : acc = 0.9210526315789473
3 , 4 : acc = 0.9210526315789473


In [143]:
params = {
    'max_depth':[1,2,3],
    'min_samples_split':[2,3,4]
}

In [144]:
from sklearn.model_selection import GridSearchCV

In [145]:
dt = DecisionTreeClassifier()
gs = GridSearchCV(dt,param_grid=params,cv=3,refit=True)
gs.fit(x_train,y_train)

GridSearchCV(cv=3, estimator=DecisionTreeClassifier(),
             param_grid={'max_depth': [1, 2, 3],
                         'min_samples_split': [2, 3, 4]})

In [146]:
gs.best_params_

{'max_depth': 2, 'min_samples_split': 4}

In [147]:
gs.best_score_

0.9551920341394026

In [148]:
model = gs.best_estimator_

In [149]:
pred = model.predict(x_test)
accuracy_score(y_test,pred)

0.9210526315789473

## 전처리

In [150]:
from sklearn.preprocessing import LabelEncoder

In [152]:
items = ['TV','냉장고',
         '전자레인지','컴퓨터',
         '선풍기','선풍기',
         '믹서','믹서']

In [154]:
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
labels

array([0, 1, 4, 5, 3, 3, 2, 2])

In [157]:
items2 = ['TV','TV','냉장고','선풍기']
labels = encoder.transform(items2)
labels

array([0, 0, 1, 3])

In [159]:
#items3 = ['식기세척기','스타일러','슈즈스타일러']
#labels = encoder.transform(items3)
#labels

In [160]:
from sklearn.preprocessing import OneHotEncoder

In [163]:
items = np.array(items).reshape(-1,1)

In [169]:
ohe = OneHotEncoder()
ohe.fit(items)
labels = ohe.transform(items)
labels.toarray()

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.]])

In [171]:
items = ['TV','냉장고',
         '전자레인지','컴퓨터',
         '선풍기','선풍기',
         '믹서','믹서']
df = pd.get_dummies(items)
df

TV  냉장고  믹서  선풍기  전자레인지  컴퓨터
0   1    0   0    0      0    0
1   0    1   0    0      0    0
2   0    0   0    0      1    0
3   0    0   0    0      0    1
4   0    0   0    1      0    0
5   0    0   0    1      0    0
6   0    0   1    0      0    0
7   0    0   1    0      0    0

In [172]:
from scipy import stats

In [177]:
heights = stats.norm.rvs(loc=173,scale=4,size=1000)
bmis = stats.norm.rvs(loc=21,scale=2,size=1000)
weights = bmis*(heights**2)/10000

In [182]:
c_sizes = [ (heights[i]*2+weights[i]*2)/5  for i in range(1000)]
c_sizes = np.array(c_sizes)

In [183]:
from sklearn.neighbors import KNeighborsRegressor

In [184]:
df = pd.DataFrame()
df['height'] = heights
df['weight'] = weights
data = df.values

In [187]:
label = c_sizes

In [188]:
x_train, x_test, y_train, y_test = train_test_split(data,label)

In [189]:
knn = KNeighborsRegressor()
knn.fit(x_train,y_train)

KNeighborsRegressor()

In [190]:
knn.score(x_test,y_test)

0.9976127488907287

In [197]:
df = pd.DataFrame()
df['height'] = heights/100
df['weight'] = weights
data = df.values

In [198]:
x_train, x_test, y_train, y_test = train_test_split(data,label)

In [199]:
knn = KNeighborsRegressor()
knn.fit(x_train,y_train)
knn.score(x_test,y_test)

0.8694065894966875

In [202]:
df = pd.DataFrame(iris.data,columns=iris.feature_names)
df.mean()

sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

In [203]:
df.var()

sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64

In [204]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler

In [208]:
ss = StandardScaler()
ss.fit(df)
scaled = ss.transform(df)
np.round(scaled.mean(),10), scaled.var()

(-0.0, 1.0)

In [214]:
df2 = pd.DataFrame(scaled)
filter = df2[0]<-3
filter.value_counts()

False    150
Name: 0, dtype: int64

In [215]:
df2.describe()

0             1             2             3
count  1.500000e+02  1.500000e+02  1.500000e+02  1.500000e+02
mean  -1.468455e-15 -1.823726e-15 -1.610564e-15 -9.473903e-16
std    1.003350e+00  1.003350e+00  1.003350e+00  1.003350e+00
min   -1.870024e+00 -2.433947e+00 -1.567576e+00 -1.447076e+00
25%   -9.006812e-01 -5.923730e-01 -1.226552e+00 -1.183812e+00
50%   -5.250608e-02 -1.319795e-01  3.364776e-01  1.325097e-01
75%    6.745011e-01  5.586108e-01  7.627583e-01  7.906707e-01
max    2.492019e+00  3.090775e+00  1.785832e+00  1.712096e+00

In [216]:
mms = MinMaxScaler()
mms.fit(df)
scaled = mms.transform(df)
df3 = pd.DataFrame(scaled)
df3.describe()

0           1           2           3
count  150.000000  150.000000  150.000000  150.000000
mean     0.428704    0.440556    0.467458    0.458056
std      0.230018    0.181611    0.299203    0.317599
min      0.000000    0.000000    0.000000    0.000000
25%      0.222222    0.333333    0.101695    0.083333
50%      0.416667    0.416667    0.567797    0.500000
75%      0.583333    0.541667    0.694915    0.708333
max      1.000000    1.000000    1.000000    1.000000

In [217]:
mms = MinMaxScaler()
mms.fit(data)
scaled_data = mms.transform(data)

x_train, x_test, y_train, y_test = train_test_split(scaled_data,label)
knn = KNeighborsRegressor()
knn.fit(x_train,y_train)
knn.score(x_test,y_test)

0.9977486406751818

In [218]:
x_train, x_test, y_train, y_test = train_test_split(data,label)

In [227]:
mms1 = MinMaxScaler()
mms1.fit(x_train)
scaled_train = mms1.transform(x_train)

In [228]:
mms2 = MinMaxScaler()
mms2.fit(x_test)
scaled_test = mms2.transform(x_test)

In [229]:
sample = [[1.75,89],[1.72,62]]
mms1.transform(sample)

array([[0.60385471, 1.08691495],
       [0.48162086, 0.45988069]])

In [230]:
mms2.transform(sample)

array([[0.56776382, 1.20300756],
       [0.41938159, 0.46335211]])